version: '3.5'

volumes:
    esdata:
        driver: local
    kibanadata:
        driver: local
    redisdata:
        driver: local
    mysqldata:
        driver: local

networks:
    apisearch:

services:

    #
    # ELK
    #
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        container_name: apisearch.elasticsearch
        networks: [apisearch]
        environment:
            - discovery.type=single-node
            - cluster.name=apisearch
            - http.host=0.0.0.0
            - transport.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "action.auto_create_index=-apisearch*,+*"
            - node.max_local_storage_nodes=10
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"

    logstash:
        image: docker.elastic.co/logstash/logstash:7.4.2
        container_name: apisearch.logstash
        networks: [apisearch]
        volumes:
            - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
            - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
            - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml

    kibana:
        image: docker.elastic.co/kibana/kibana:7.4.2
        container_name: apisearch.kibana
        networks: [apisearch]
        environment:
            ELASTICSEARCH_URL: http://apisearch.elasticsearch:9200
        ports:
            - "5601:5601"

    #
    # Persistence infrastructure
    #
    amqp:
        image: "rabbitmq:3-management"
        container_name: apisearch.amqp
        networks: [apisearch]
        ports:
            - "15672:15672"

    redis:
        image: redis:4-alpine
        container_name: apisearch.redis
        networks: [apisearch]
        volumes:
            - redisdata:/data

    mysql:
        image: mysql:5
        container_name: apisearch.mysql
        networks: [apisearch]
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: apisearch
        ports:
            - "3306:3306"
        volumes:
            - mysqldata:/var/lib/mysql
            - ./mysql/token.sql:/docker-entrypoint-initdb.d/token.sql


    #
    # Apisearch containers
    #
    tiny_balancer:
        image: "driftphp/tiny-balancer"
        ports:
            - "${APISEARCH_SERVER_PORT}:8000"
        networks: [apisearch]
        entrypoint: ["php", "balancer", "8000", "apisearch.server_1:8000", "apisearch.server_2:8000", "apisearch.server_3:8000"]

    server_1:
        image: apisearchio/search-server:latest
        container_name: apisearch.server_1
        networks: [apisearch]
        command: ["sh", /wait-and-run.sh, /create-infrastructure.sh, /server-entrypoint.sh]
        volumes:
            - ./wait/wait-and-run.sh:/wait-and-run.sh
        env_file:
            - ./.env

    server_2:
        image: apisearchio/search-server:latest
        container_name: apisearch.server_2
        networks: [apisearch]
        command: ["sh", /wait-and-run.sh, /create-infrastructure.sh, /server-entrypoint.sh]
        volumes:
            - ./wait/wait-and-run.sh:/wait-and-run.sh
        env_file:
            - ./.env

    server_3:
        image: apisearchio/search-server:latest
        container_name: apisearch.server_3
        networks: [apisearch]
        command: ["sh", /wait-and-run.sh, /create-infrastructure.sh, /server-entrypoint.sh]
        volumes:
            - ./wait/wait-and-run.sh:/wait-and-run.sh
        env_file:
            - ./.env


